services:
  web:
    build:
      context: .
    container_name: django-anegen-cont
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,anecgenerator.lat,anegen.lat,django-docker-tj2p.onrender.com,anegen.onrender.com
      - OPENAI_API_KEY=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
  nginx:
    image: nginx:latest
    container_name: nginx-cont
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web