# Generated by Django 5.1.4 on 2025-09-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=50)),
                ('type', models.CharField(default='none', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='joke',
            old_name='joke',
            new_name='text',
        ),
        migrations.AddField(
            model_name='joke',
            name='type',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
