# Generated by Django 5.1.4 on 2026-04-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_quote_rename_joke_joke_text_joke_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
