# Generated by Django 5.1.4 on 2026-04-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_delete_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
