# Generated by Django 5.1.4 on 2026-04-28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0004_joke_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joke',
            name='type',
        ),
    ]
